---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres
  namespace: quay-enterprise
  labels:
    app: postgres
spec:
  # Only one instance of the postgres database is defined here. Adjust replicas based on demand.
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 0 
        fsGroup: 0
      containers:
        - name: postgres
          image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1-35 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            # Replace "username" with a name for your Postgres user
            value: "username"
          - name: POSTGRES_DATABASE
            # Replace "password" with a password for your Postgres user
            value: "quay"
          - name: POSTGRES_PASSWORD
            value: "password"
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgredb
      serviceAccount: postgres
      serviceAccountName: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-storage
